# Generated by Django 5.2.1 on 2025-06-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='picture',
        ),
    ]
